
name: CD/CD Pipeline

on: 
  push:
    branches: [ master ]
  pull_request:

jobs:
  run-app:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Verify files exist
        run: |
          echo "Listing project files:"
          ls -la
      
          
      - name: Run app.js
        run: node app.js && echo "Running app.js..."
  
          

